# Generated by Django 6.0 on 2025-12-28 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When the measurement was taken')),
                ('pm25', models.DecimalField(blank=True, decimal_places=2, help_text='PM2.5 - Fine particulate matter (µg/m³)', max_digits=7, null=True)),
                ('pm10', models.DecimalField(blank=True, decimal_places=2, help_text='PM10 - Coarse particulate matter (µg/m³)', max_digits=7, null=True)),
                ('no2', models.DecimalField(blank=True, decimal_places=2, help_text='Nitrogen Dioxide (µg/m³)', max_digits=7, null=True)),
                ('o3', models.DecimalField(blank=True, decimal_places=2, help_text='Ozone (µg/m³)', max_digits=7, null=True)),
                ('co', models.DecimalField(blank=True, decimal_places=2, help_text='Carbon Monoxide (mg/m³)', max_digits=7, null=True)),
                ('so2', models.DecimalField(blank=True, decimal_places=2, help_text='Sulfur Dioxide (µg/m³)', max_digits=7, null=True)),
                ('aqi', models.IntegerField(blank=True, help_text='Air Quality Index (0-500)', null=True)),
                ('source', models.CharField(blank=True, help_text='Data source (e.g., API, sensor)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_readings', to='schools.school')),
            ],
            options={
                'verbose_name': 'Air Quality Reading',
                'verbose_name_plural': 'Air Quality Readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['school', '-timestamp'], name='airquality__school__80a897_idx')],
            },
        ),
    ]
