# Generated by Django 6.0 on 2026-01-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_options_school_borough_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='laei_data_available',
            field=models.BooleanField(default=False, help_text='LAEI pollution data available'),
        ),
        migrations.AddField(
            model_name='school',
            name='no2_2022',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='NO₂ concentration µg/m³', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='nox_2022',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='NOₓ concentration µg/m³', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='pm10_days_2022',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PM10 days exceeding limit', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='pm10_mean_2022',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PM10 annual mean µg/m³', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='pm25_2022',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PM2.5 concentration µg/m³', max_digits=6, null=True),
        ),
    ]
