# Generated by Django 6.0 on 2026-01-15 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_laei_data_available_school_no2_2022_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('network', models.CharField(choices=[('LAQN', 'London Air Quality Network'), ('BREATHE', 'Breathe London')], db_index=True, max_length=20)),
                ('site_type', models.CharField(choices=[('roadside', 'Roadside'), ('urban_background', 'Urban Background'), ('suburban', 'Suburban'), ('industrial', 'Industrial'), ('kerbside', 'Kerbside')], default='urban_background', max_length=30)),
                ('borough', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['network', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AddField(
            model_name='school',
            name='data_source',
            field=models.CharField(choices=[('DIRECT', 'Direct Sensor Reading'), ('ADJUSTED', 'LAEI Adjusted by Sensor'), ('LAEI', 'LAEI Baseline Only')], default='LAEI', help_text='Current data methodology', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='direct_sensor_distance',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Distance to direct sensor in meters', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='reference_sensor_distance',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Distance to reference sensor in meters', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='direct_sensor',
            field=models.ForeignKey(blank=True, help_text='Urban background sensor within 150m', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_schools', to='schools.sensor'),
        ),
        migrations.AddField(
            model_name='school',
            name='reference_sensor',
            field=models.ForeignKey(blank=True, help_text='Nearest LAQN sensor for adjustment factors', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_schools', to='schools.sensor'),
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('no2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pm25', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pm10', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('o3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nox', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='schools.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('sensor', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='SensorAnnualStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('no2_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pm25_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pm10_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('o3_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('capture_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_stats', to='schools.sensor')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('sensor', 'year')},
            },
        ),
    ]
