# Generated by Django 6.0 on 2026-01-28 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0002_remove_school_air_quality_borough_9c4490_idx_and_more'),
        ('schools', '0004_sensor_alter_school_options_school_data_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='direct_sensor',
            field=models.ForeignKey(blank=True, help_text='Urban background sensor within 150m', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_schools', to='air_quality.sensor'),
        ),
        migrations.AlterField(
            model_name='school',
            name='reference_sensor',
            field=models.ForeignKey(blank=True, help_text='Nearest LAQN sensor for adjustment factors', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_schools', to='air_quality.sensor'),
        ),
    ]

