# Generated by Django 4.2.28 on 2026-02-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_school_direct_sensor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensorannualstats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sensorannualstats',
            name='sensor',
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='SensorAnnualStats',
        ),
    ]
