# Generated by Django 4.2.28 on 2026-02-22 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0006_alter_sensorannualstats_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Share observations about air quality conditions at this school.')),
                ('category', models.CharField(choices=[('observation', 'General Observation'), ('concern', 'Air Quality Concern'), ('improvement', 'Improvement Suggestion'), ('update', 'School Environment Update')], default='observation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_notes', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Note',
                'verbose_name_plural': 'School Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
