# Generated by Django 6.0 on 2026-10-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildcareSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, help_text='Blank for home-based providers (withheld by Ofsted)', max_length=255)),
                ('provider_type', models.CharField(choices=[('non_domestic', 'Childcare on non-domestic premises'), ('childminder', 'Childminder'), ('domestic', 'Childcare on domestic premises')], max_length=20)),
                ('register_combination', models.CharField(blank=True, help_text='EYR only / EYR-CCR / ALL', max_length=20)),
                ('places', models.IntegerField(blank=True, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('borough', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('easting', models.IntegerField(blank=True, null=True)),
                ('northing', models.IntegerField(blank=True, null=True)),
                ('lsoa21', models.CharField(blank=True, help_text='2021-boundary LSOA code, for IMD/IDACI joins', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider_type', 'name'],
            },
        ),
    ]
