# Generated by Django 6.0 on 2026-01-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='school',
            name='air_quality_borough_9c4490_idx',
        ),
        migrations.RemoveIndex(
            model_name='school',
            name='air_quality_data_so_ff4501_idx',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
